title: <p align="center"> Peter Okeke </p>

logo: "/images/Picture3.jpg?raw=true"

description: >
  <p align="center">
  <a href="pdf/PeterChukwunwenduOkekeResume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/peter-okeke/">LinkedIn</a> |
  <a href="https://github.com/ItsPietro">GitHub</a>
  </p>
  
  <p align="justify">
  I am passionate about leveraging data-driven insights to solve complex problems and drive strategic decision making.
  <br><br>
  I am interested in developing my skills in Machine Learning to advance my career in data science.
  <br><br>
  </p>
   
show_downloads: true  
theme: jekyll-theme-minimal
