title: <p align="center"> Peter Okeke </p>

logo: <a href="url"><img src="/images/Peter_Okeke.jpg?raw=true" height="auto" width="200" style="border-radius:50%"></a>

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/peter-okeke/">LinkedIn</a> |
  <a href="https://github.com/ItsPietro">GitHub</a>
  </p>
  
  <p align="justify">
  I am passionate about leveraging data-driven insights to solve complex problems and drive strategic decision making.
  <br><br>
  </p>
   
show_downloads: true  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
